version: '3'

services:
  cozoomus:
    #image: xezpeleta/cozoomus
    build: .
    env_file: .env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"